/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Logic.*;
import java.awt.Component;
import java.awt.Container;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.border.Border;
import javax.swing.plaf.basic.BasicBorders;

/**
 *
 * @author ffoof
 */
public class SportSystem extends javax.swing.JFrame {

    /**
     * Creates new form Report
     */
    League league = new League("Sport League");

    public SportSystem() {
        initComponents();
        txtmanagerTeam.addItem("Unassigne");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addManager = new javax.swing.JDialog();
        btnCancelAddManager = new javax.swing.JButton();
        btnSaveAddManager = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtmanagerName = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtmanagerAddress = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtmanagerBonus = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        SpinnerSalary = new javax.swing.JSpinner();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtmanagerTeam = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtmanagerQuali = new javax.swing.JTextArea();
        txtmanagerDOB = new javax.swing.JTextField();
        SMonth = new javax.swing.JSpinner();
        SDay = new javax.swing.JSpinner();
        SYear = new javax.swing.JSpinner();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        EditAndDeleteManager = new javax.swing.JDialog();
        btnCancelAddManager1 = new javax.swing.JButton();
        btnSaveAddManager1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtmanagerNameOut = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtmanagerAddressOut = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtmanagerBonusOut = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtmanagerSalaryOut = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtmanagerDOBOut = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtmanagerTeamOut = new javax.swing.JComboBox<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtmanagerQualiOut = new javax.swing.JTextArea();
        txtmanagerNationalityOut1 = new javax.swing.JTextField();
        btnCancelAddManager2 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        txtID = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblSportSystem = new javax.swing.JLabel();
        lblListAllMembers = new javax.swing.JLabel();
        lblManageTeams = new javax.swing.JLabel();
        lblManageManagers = new javax.swing.JLabel();
        lblManagePlayer = new javax.swing.JLabel();
        lblGenerateReports = new javax.swing.JLabel();
        lblStatsAndAnalysis = new javax.swing.JLabel();
        Parent = new javax.swing.JPanel();
        Dashbord = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ListAllMembers = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ManageTeams = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ManageManagers = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnAddTeam = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ManagerSearch = new javax.swing.JTextField();
        SearchBy = new javax.swing.JComboBox<>();
        ManagePlayer = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        GenerateReports = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnYearlyReport = new javax.swing.JButton();
        btnFortnightlyReport = new javax.swing.JButton();
        btnMonthlyReport = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        YReport = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnExportY = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        MReport = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnExportM = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        FReport = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnExportF = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        StatsAndAnalysis = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();

        addManager.setMinimumSize(new java.awt.Dimension(1038, 700));

        btnCancelAddManager.setBackground(new java.awt.Color(57, 88, 134));
        btnCancelAddManager.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnCancelAddManager.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelAddManager.setText("Cancel");
        btnCancelAddManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelAddManagerActionPerformed(evt);
            }
        });

        btnSaveAddManager.setBackground(new java.awt.Color(160, 160, 160));
        btnSaveAddManager.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnSaveAddManager.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveAddManager.setText("Save");
        btnSaveAddManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAddManagerActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel12.setText("Add Manager");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Name");

        txtmanagerName.setBackground(new java.awt.Color(160, 160, 160));
        txtmanagerName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Address");

        txtmanagerAddress.setBackground(new java.awt.Color(160, 160, 160));
        txtmanagerAddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Bonus percentage ");

        txtmanagerBonus.setBackground(new java.awt.Color(160, 160, 160));
        txtmanagerBonus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Yearly Salary");

        SpinnerSalary.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SpinnerSalary.setModel(new javax.swing.SpinnerNumberModel());

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(txtmanagerName, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addComponent(txtmanagerAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                    .addComponent(jLabel14)
                    .addComponent(txtmanagerBonus, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                    .addComponent(jLabel15)
                    .addComponent(SpinnerSalary))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmanagerName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmanagerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmanagerBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SpinnerSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Date of Birth");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Nationality");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("Team");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setText("Qualification Description");

        txtmanagerTeam.setBackground(new java.awt.Color(160, 160, 160));
        txtmanagerTeam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtmanagerTeam.setName(""); // NOI18N

        txtmanagerQuali.setBackground(new java.awt.Color(160, 160, 160));
        txtmanagerQuali.setColumns(20);
        txtmanagerQuali.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtmanagerQuali.setRows(5);
        jScrollPane5.setViewportView(txtmanagerQuali);

        txtmanagerDOB.setBackground(new java.awt.Color(160, 160, 160));
        txtmanagerDOB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtmanagerDOB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtmanagerDOBFocusGained(evt);
            }
        });

        SMonth.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SMonth.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        SDay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SDay.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        SYear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SYear.setModel(new javax.swing.SpinnerNumberModel(2024, 1800, 2024, 1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("Day");

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setText("Month");

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setText("Year");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SDay, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SYear, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addComponent(jLabel23)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(txtmanagerDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20))
                                .addComponent(txtmanagerTeam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmanagerDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SDay, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SYear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmanagerTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout addManagerLayout = new javax.swing.GroupLayout(addManager.getContentPane());
        addManager.getContentPane().setLayout(addManagerLayout);
        addManagerLayout.setHorizontalGroup(
            addManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addManagerLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(addManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addManagerLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 365, Short.MAX_VALUE)
                        .addComponent(btnCancelAddManager, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnSaveAddManager, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(addManagerLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
        );
        addManagerLayout.setVerticalGroup(
            addManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addManagerLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(addManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelAddManager, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(btnSaveAddManager, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(addManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        EditAndDeleteManager.setMinimumSize(new java.awt.Dimension(1038, 700));

        btnCancelAddManager1.setBackground(new java.awt.Color(57, 88, 134));
        btnCancelAddManager1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnCancelAddManager1.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelAddManager1.setText("Cancel");
        btnCancelAddManager1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelAddManager1ActionPerformed(evt);
            }
        });

        btnSaveAddManager1.setBackground(new java.awt.Color(160, 160, 160));
        btnSaveAddManager1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnSaveAddManager1.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveAddManager1.setText("Save");
        btnSaveAddManager1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAddManager1ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel16.setText("Manager Details");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Name");

        txtmanagerNameOut.setBackground(new java.awt.Color(160, 160, 160));
        txtmanagerNameOut.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Address");

        txtmanagerAddressOut.setBackground(new java.awt.Color(160, 160, 160));
        txtmanagerAddressOut.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Bonus percentage ");

        txtmanagerBonusOut.setBackground(new java.awt.Color(160, 160, 160));
        txtmanagerBonusOut.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setText("Yearly Salary");

        txtmanagerSalaryOut.setBackground(new java.awt.Color(160, 160, 160));
        txtmanagerSalaryOut.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(txtmanagerNameOut, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txtmanagerAddressOut, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(txtmanagerBonusOut, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(txtmanagerSalaryOut, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmanagerNameOut, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmanagerAddressOut, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmanagerBonusOut, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmanagerSalaryOut, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setText("Date of Birth");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel26.setText("Nationality");

        txtmanagerDOBOut.setBackground(new java.awt.Color(160, 160, 160));
        txtmanagerDOBOut.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel27.setText("Team");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel28.setText("Qualification Description");

        txtmanagerTeamOut.setBackground(new java.awt.Color(160, 160, 160));
        txtmanagerTeamOut.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtmanagerTeamOut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtmanagerQualiOut.setBackground(new java.awt.Color(160, 160, 160));
        txtmanagerQualiOut.setColumns(20);
        txtmanagerQualiOut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtmanagerQualiOut.setRows(5);
        jScrollPane6.setViewportView(txtmanagerQualiOut);

        txtmanagerNationalityOut1.setBackground(new java.awt.Color(160, 160, 160));
        txtmanagerNationalityOut1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(txtmanagerDOBOut, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(txtmanagerTeamOut, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(txtmanagerNationalityOut1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addComponent(txtmanagerNationalityOut1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmanagerDOBOut, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmanagerTeamOut, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        btnCancelAddManager2.setBackground(new java.awt.Color(89, 9, 9));
        btnCancelAddManager2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnCancelAddManager2.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelAddManager2.setText("Delete");
        btnCancelAddManager2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelAddManager2ActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel29.setText("ID: ");

        txtID.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtID.setText("0000");

        javax.swing.GroupLayout EditAndDeleteManagerLayout = new javax.swing.GroupLayout(EditAndDeleteManager.getContentPane());
        EditAndDeleteManager.getContentPane().setLayout(EditAndDeleteManagerLayout);
        EditAndDeleteManagerLayout.setHorizontalGroup(
            EditAndDeleteManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditAndDeleteManagerLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(EditAndDeleteManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EditAndDeleteManagerLayout.createSequentialGroup()
                        .addGap(511, 511, 511)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(52, Short.MAX_VALUE))
                    .addGroup(EditAndDeleteManagerLayout.createSequentialGroup()
                        .addGroup(EditAndDeleteManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, EditAndDeleteManagerLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelAddManager2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnCancelAddManager1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnSaveAddManager1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))))
            .addGroup(EditAndDeleteManagerLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        EditAndDeleteManagerLayout.setVerticalGroup(
            EditAndDeleteManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditAndDeleteManagerLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(EditAndDeleteManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelAddManager1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(btnSaveAddManager1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelAddManager2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 25, Short.MAX_VALUE)
                .addGroup(EditAndDeleteManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addGroup(EditAndDeleteManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1321, 750));
        setPreferredSize(new java.awt.Dimension(1321, 750));
        setSize(new java.awt.Dimension(1321, 750));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(57, 88, 134));

        lblSportSystem.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        lblSportSystem.setForeground(new java.awt.Color(255, 255, 255));
        lblSportSystem.setText("Sport System");
        lblSportSystem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSportSystemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblmouseEnter(evt);
            }
        });

        lblListAllMembers.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblListAllMembers.setForeground(new java.awt.Color(255, 255, 255));
        lblListAllMembers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/image/Performance Macbook.png"))); // NOI18N
        lblListAllMembers.setText(" List All Members");
        lblListAllMembers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblListAllMembersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblmouseEnter(evt);
            }
        });

        lblManageTeams.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblManageTeams.setForeground(new java.awt.Color(255, 255, 255));
        lblManageTeams.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/image/Crowd.png"))); // NOI18N
        lblManageTeams.setText(" Manage Teams");
        lblManageTeams.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblManageTeamsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblmouseEnter(evt);
            }
        });

        lblManageManagers.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblManageManagers.setForeground(new java.awt.Color(255, 255, 255));
        lblManageManagers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/image/Administrator Male.png"))); // NOI18N
        lblManageManagers.setText(" Manage Managers");
        lblManageManagers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblManageManagersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblmouseEnter(evt);
            }
        });

        lblManagePlayer.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblManagePlayer.setForeground(new java.awt.Color(255, 255, 255));
        lblManagePlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/image/Soccer.png"))); // NOI18N
        lblManagePlayer.setText(" Manage Player");
        lblManagePlayer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblManagePlayerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblmouseEnter(evt);
            }
        });

        lblGenerateReports.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblGenerateReports.setForeground(new java.awt.Color(255, 255, 255));
        lblGenerateReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/image/Health Graph.png"))); // NOI18N
        lblGenerateReports.setText(" Generate Reports");
        lblGenerateReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGenerateReportsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblmouseEnter(evt);
            }
        });

        lblStatsAndAnalysis.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblStatsAndAnalysis.setForeground(new java.awt.Color(255, 255, 255));
        lblStatsAndAnalysis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/image/Combo Chart.png"))); // NOI18N
        lblStatsAndAnalysis.setText(" Stats & Analysis");
        lblStatsAndAnalysis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStatsAndAnalysisMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblmouseEnter(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSportSystem)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblListAllMembers)
                        .addComponent(lblManageTeams)
                        .addComponent(lblManageManagers)
                        .addComponent(lblManagePlayer)
                        .addComponent(lblGenerateReports)
                        .addComponent(lblStatsAndAnalysis)))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblSportSystem)
                .addGap(63, 63, 63)
                .addComponent(lblListAllMembers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(lblManageTeams)
                .addGap(64, 64, 64)
                .addComponent(lblManageManagers)
                .addGap(75, 75, 75)
                .addComponent(lblManagePlayer)
                .addGap(70, 70, 70)
                .addComponent(lblGenerateReports)
                .addGap(67, 67, 67)
                .addComponent(lblStatsAndAnalysis)
                .addGap(60, 60, 60))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 280, 750);

        Parent.setBackground(new java.awt.Color(255, 255, 255));
        Parent.setLayout(new java.awt.CardLayout());

        Dashbord.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("Dashbord");

        javax.swing.GroupLayout DashbordLayout = new javax.swing.GroupLayout(Dashbord);
        Dashbord.setLayout(DashbordLayout);
        DashbordLayout.setHorizontalGroup(
            DashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashbordLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel3)
                .addContainerGap(812, Short.MAX_VALUE))
        );
        DashbordLayout.setVerticalGroup(
            DashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashbordLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addContainerGap(637, Short.MAX_VALUE))
        );

        Parent.add(Dashbord, "card2");

        ListAllMembers.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("List All Members");

        javax.swing.GroupLayout ListAllMembersLayout = new javax.swing.GroupLayout(ListAllMembers);
        ListAllMembers.setLayout(ListAllMembersLayout);
        ListAllMembersLayout.setHorizontalGroup(
            ListAllMembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListAllMembersLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel4)
                .addContainerGap(705, Short.MAX_VALUE))
        );
        ListAllMembersLayout.setVerticalGroup(
            ListAllMembersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListAllMembersLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addContainerGap(637, Short.MAX_VALUE))
        );

        Parent.add(ListAllMembers, "card2");

        ManageTeams.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("Manage Teams");

        javax.swing.GroupLayout ManageTeamsLayout = new javax.swing.GroupLayout(ManageTeams);
        ManageTeams.setLayout(ManageTeamsLayout);
        ManageTeamsLayout.setHorizontalGroup(
            ManageTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageTeamsLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel5)
                .addContainerGap(723, Short.MAX_VALUE))
        );
        ManageTeamsLayout.setVerticalGroup(
            ManageTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageTeamsLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addContainerGap(637, Short.MAX_VALUE))
        );

        Parent.add(ManageTeams, "card2");

        ManageManagers.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 42)); // NOI18N
        jLabel6.setText("Manage Managers");

        btnAddTeam.setBackground(new java.awt.Color(213, 222, 239));
        btnAddTeam.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnAddTeam.setText("Add Manager");
        btnAddTeam.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAddTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddManagerActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        ManagerSearch.setBackground(new java.awt.Color(217, 217, 217));
        ManagerSearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ManagerSearch.setForeground(new java.awt.Color(153, 153, 153));
        ManagerSearch.setText("Search by ID or name or team ");
        ManagerSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ManagerSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ManagerSearchFocusLost(evt);
            }
        });

        SearchBy.setBackground(new java.awt.Color(160, 160, 160));
        SearchBy.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SearchBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Name", "Team" }));

        javax.swing.GroupLayout ManageManagersLayout = new javax.swing.GroupLayout(ManageManagers);
        ManageManagers.setLayout(ManageManagersLayout);
        ManageManagersLayout.setHorizontalGroup(
            ManageManagersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageManagersLayout.createSequentialGroup()
                .addGroup(ManageManagersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ManageManagersLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(ManageManagersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ManageManagersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(ManageManagersLayout.createSequentialGroup()
                                    .addComponent(ManagerSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(SearchBy, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnAddTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ManageManagersLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel6)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        ManageManagersLayout.setVerticalGroup(
            ManageManagersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageManagersLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel6)
                .addGap(81, 81, 81)
                .addComponent(btnAddTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(ManageManagersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ManagerSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchBy, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        Parent.add(ManageManagers, "card2");

        ManagePlayer.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 42)); // NOI18N
        jLabel7.setText("Manage Player");

        javax.swing.GroupLayout ManagePlayerLayout = new javax.swing.GroupLayout(ManagePlayer);
        ManagePlayer.setLayout(ManagePlayerLayout);
        ManagePlayerLayout.setHorizontalGroup(
            ManagePlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManagePlayerLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel7)
                .addContainerGap(718, Short.MAX_VALUE))
        );
        ManagePlayerLayout.setVerticalGroup(
            ManagePlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManagePlayerLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addContainerGap(630, Short.MAX_VALUE))
        );

        Parent.add(ManagePlayer, "card2");

        GenerateReports.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 42)); // NOI18N
        jLabel10.setText("Generate Reports");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnYearlyReport.setBackground(new java.awt.Color(213, 222, 239));
        btnYearlyReport.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnYearlyReport.setText("Yearly Report ");
        btnYearlyReport.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnYearlyReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYearlyReportActionPerformed(evt);
            }
        });

        btnFortnightlyReport.setBackground(new java.awt.Color(213, 222, 239));
        btnFortnightlyReport.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnFortnightlyReport.setText("Fortnightly Report");
        btnFortnightlyReport.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnFortnightlyReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFortnightlyReportActionPerformed(evt);
            }
        });

        btnMonthlyReport.setBackground(new java.awt.Color(213, 222, 239));
        btnMonthlyReport.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnMonthlyReport.setText("Monthly Report ");
        btnMonthlyReport.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMonthlyReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonthlyReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnYearlyReport, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnMonthlyReport, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnFortnightlyReport, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnYearlyReport, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFortnightlyReport, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMonthlyReport, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "League", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 36), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 881, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout GenerateReportsLayout = new javax.swing.GroupLayout(GenerateReports);
        GenerateReports.setLayout(GenerateReportsLayout);
        GenerateReportsLayout.setHorizontalGroup(
            GenerateReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GenerateReportsLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(GenerateReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        GenerateReportsLayout.setVerticalGroup(
            GenerateReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GenerateReportsLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel10)
                .addGap(45, 45, 45)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        Parent.add(GenerateReports, "card2");

        YReport.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Yearly Report");

        btnExportY.setBackground(new java.awt.Color(79, 104, 140));
        btnExportY.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnExportY.setForeground(new java.awt.Color(255, 255, 255));
        btnExportY.setText("Export");
        btnExportY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportYActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout YReportLayout = new javax.swing.GroupLayout(YReport);
        YReport.setLayout(YReportLayout);
        YReportLayout.setHorizontalGroup(
            YReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(YReportLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel2)
                .addContainerGap(749, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, YReportLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExportY, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
            .addGroup(YReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(YReportLayout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(119, Short.MAX_VALUE)))
        );
        YReportLayout.setVerticalGroup(
            YReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(YReportLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(42, 42, 42)
                .addComponent(btnExportY, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(552, Short.MAX_VALUE))
            .addGroup(YReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(YReportLayout.createSequentialGroup()
                    .addGap(186, 186, 186)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(261, Short.MAX_VALUE)))
        );

        Parent.add(YReport, "card2");

        MReport.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setText("Monthly Report ");

        btnExportM.setBackground(new java.awt.Color(79, 104, 140));
        btnExportM.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnExportM.setForeground(new java.awt.Color(255, 255, 255));
        btnExportM.setText("Export");
        btnExportM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportMActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout MReportLayout = new javax.swing.GroupLayout(MReport);
        MReport.setLayout(MReportLayout);
        MReportLayout.setHorizontalGroup(
            MReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MReportLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel9)
                .addContainerGap(710, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MReportLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExportM, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
            .addGroup(MReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MReportLayout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(119, Short.MAX_VALUE)))
        );
        MReportLayout.setVerticalGroup(
            MReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MReportLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel9)
                .addGap(42, 42, 42)
                .addComponent(btnExportM, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(552, Short.MAX_VALUE))
            .addGroup(MReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MReportLayout.createSequentialGroup()
                    .addGap(186, 186, 186)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(261, Short.MAX_VALUE)))
        );

        btnExportM.getAccessibleContext().setAccessibleDescription("");

        Parent.add(MReport, "card2");

        FReport.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel11.setText("Fortnightly Report");

        btnExportF.setBackground(new java.awt.Color(79, 104, 140));
        btnExportF.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnExportF.setForeground(new java.awt.Color(255, 255, 255));
        btnExportF.setText("Export");
        btnExportF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportFActionPerformed(evt);
            }
        });

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        javax.swing.GroupLayout FReportLayout = new javax.swing.GroupLayout(FReport);
        FReport.setLayout(FReportLayout);
        FReportLayout.setHorizontalGroup(
            FReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FReportLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel11)
                .addContainerGap(677, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FReportLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExportF, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
            .addGroup(FReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FReportLayout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(119, Short.MAX_VALUE)))
        );
        FReportLayout.setVerticalGroup(
            FReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FReportLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel11)
                .addGap(42, 42, 42)
                .addComponent(btnExportF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(552, Short.MAX_VALUE))
            .addGroup(FReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FReportLayout.createSequentialGroup()
                    .addGap(186, 186, 186)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(261, Short.MAX_VALUE)))
        );

        Parent.add(FReport, "card2");

        StatsAndAnalysis.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setText("Stats & Analysis");

        javax.swing.GroupLayout StatsAndAnalysisLayout = new javax.swing.GroupLayout(StatsAndAnalysis);
        StatsAndAnalysis.setLayout(StatsAndAnalysisLayout);
        StatsAndAnalysisLayout.setHorizontalGroup(
            StatsAndAnalysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatsAndAnalysisLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel8)
                .addContainerGap(712, Short.MAX_VALUE))
        );
        StatsAndAnalysisLayout.setVerticalGroup(
            StatsAndAnalysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatsAndAnalysisLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel8)
                .addContainerGap(637, Short.MAX_VALUE))
        );

        Parent.add(StatsAndAnalysis, "card2");

        getContentPane().add(Parent);
        Parent.setBounds(280, 40, 1040, 710);

        jPanel4.setBackground(new java.awt.Color(98, 142, 203));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/image/solar_settings-broken.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel30)
                .addContainerGap(1007, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(280, 0, 1040, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMonthlyReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonthlyReportActionPerformed
        // TODO add your handling code here:
        setAllComponentsVisible(false);

        MReport.setVisible(true);

    }//GEN-LAST:event_btnMonthlyReportActionPerformed

    private void lblmouseEnter(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmouseEnter
        // TODO add your handling code here:
        lblListAllMembers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblManageTeams.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblManageManagers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblManagePlayer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGenerateReports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblStatsAndAnalysis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSportSystem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblmouseEnter

    private void lblGenerateReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGenerateReportsMouseClicked
        // TODO add your handling code here:
        setAllComponentsVisible(false);

        GenerateReports.setVisible(true);

    }//GEN-LAST:event_lblGenerateReportsMouseClicked

    private void lblSportSystemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSportSystemMouseClicked
        // TODO add your handling code here:
        setAllComponentsVisible(false);

        Dashbord.setVisible(true);

    }//GEN-LAST:event_lblSportSystemMouseClicked

    private void btnYearlyReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYearlyReportActionPerformed
        // TODO add your handling code here:
        setAllComponentsVisible(false);

        YReport.setVisible(true);

    }//GEN-LAST:event_btnYearlyReportActionPerformed

    private void lblListAllMembersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblListAllMembersMouseClicked
        // TODO add your handling code here:
        setAllComponentsVisible(false);

        ListAllMembers.setVisible(true);
    }//GEN-LAST:event_lblListAllMembersMouseClicked

    private void lblManageTeamsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageTeamsMouseClicked
        // TODO add your handling code here:
        setAllComponentsVisible(false);
        ManageTeams.setVisible(true);

    }//GEN-LAST:event_lblManageTeamsMouseClicked

    private void lblManageManagersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageManagersMouseClicked
        // TODO add your handling code here:
        setAllComponentsVisible(false);
        ManageManagers.setVisible(true);

    }//GEN-LAST:event_lblManageManagersMouseClicked

    private void lblManagePlayerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManagePlayerMouseClicked
        // TODO add your handling code here:
        setAllComponentsVisible(false);
        ManagePlayer.setVisible(true);


    }//GEN-LAST:event_lblManagePlayerMouseClicked

    private void lblStatsAndAnalysisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStatsAndAnalysisMouseClicked
        // TODO add your handling code here:
        setAllComponentsVisible(false);

        StatsAndAnalysis.setVisible(true);

    }//GEN-LAST:event_lblStatsAndAnalysisMouseClicked

    private void btnExportYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportYActionPerformed

    private void btnExportMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportMActionPerformed

    private void btnExportFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportFActionPerformed

    private void btnFortnightlyReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFortnightlyReportActionPerformed
        // TODO add your handling code here:
        setAllComponentsVisible(false);
        FReport.setVisible(true);

    }//GEN-LAST:event_btnFortnightlyReportActionPerformed

    private void btnAddManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddManagerActionPerformed
        // TODO add your handling code here:
        setAllComponentsVisible(false);
        ManageManagers.setVisible(true);
        addManager.setVisible(true);

        txtmanagerName.setText("");
        txtmanagerAddress.setText("");
        txtmanagerDOB.setText("");
//        txtmanagerNationality.setText("");
        txtmanagerBonus.setText("");

//        txtmanagerSalary.setText("");
        txtmanagerQuali.setText("");

        for (int i = 0; i < league.getTeams().size(); i++) {
            txtmanagerTeam.addItem(league.getTeams().get(i).getName());
        }

        txtmanagerTeam.setSelectedIndex(0);

        //set the placeholder value in add manager dialog
        txtmanagerDOB.setText("YYYY-MM-DD");
        txtmanagerDOB.setForeground(new java.awt.Color(51, 51, 51));

    }//GEN-LAST:event_btnAddManagerActionPerformed

    private void btnCancelAddManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelAddManagerActionPerformed
        // TODO add your handling code here:
        addManager.dispose();
    }//GEN-LAST:event_btnCancelAddManagerActionPerformed

    private void btnSaveAddManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAddManagerActionPerformed
        // TODO add your handling code here:
        //add the managr first that colse the table after completing creating the manager
        String name;
        LocalDate dob;
        String address;
        String nationality = null;
        double bounes;
        Team teamName;
        double salary = 0;
        String Qualification;
        String day, month, year;

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy"); //problem here

        name = txtmanagerName.getText();
        day = SDay.getValue().toString();
        month = SMonth.getValue().toString();
        year = SYear.getValue().toString();
        dob = LocalDate.parse(day+"/"+month+"/"+year,formatter);
        address = txtmanagerAddress.getText();
//        nationality = txtmanagerNationality.getText();
        bounes = Double.parseDouble(txtmanagerBonus.getText());
//        teamName = txtmanagerTeam.getSelectedItem().toString();
//        salary = Double.parseDouble(txtmanagerSalary.getText());
        Qualification = txtmanagerQuali.getText();

        System.out.println(name);
        System.out.println(dob);
        System.out.println(address);
        System.out.println(nationality);
        System.out.println(bounes);
//         System.out.println(team);
        System.out.println(salary);
        System.out.println(Qualification);
//  Create the manager object 
//        Manager m1 = new Manager(name, dob, address, nationality, salary, bounes, Qualification);
        JOptionPane.showMessageDialog(Parent, "The manager successful add into the system");
// make the fields empty 
        addManager.dispose();
    }//GEN-LAST:event_btnSaveAddManagerActionPerformed

    private void btnCancelAddManager1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelAddManager1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnCancelAddManager1ActionPerformed

    private void btnSaveAddManager1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAddManager1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveAddManager1ActionPerformed

    private void btnCancelAddManager2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelAddManager2ActionPerformed
        // TODO add your handling code here:
        //delete 
        EditAndDeleteManager.dispose();
    }//GEN-LAST:event_btnCancelAddManager2ActionPerformed

    private void ManagerSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ManagerSearchFocusGained
        // TODO add your handling code here:
        ManagerSearch.setText("");
        ManagerSearch.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_ManagerSearchFocusGained

    private void ManagerSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ManagerSearchFocusLost
        // TODO add your handling code here:
        ManagerSearch.setText("Search by ID or name or team ");
        ManagerSearch.setForeground(new java.awt.Color(153, 153, 153));
    }//GEN-LAST:event_ManagerSearchFocusLost

    private void txtmanagerDOBFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmanagerDOBFocusGained
        // TODO add your handling code here:
        txtmanagerDOB.setText("");
        txtmanagerDOB.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_txtmanagerDOBFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SportSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SportSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SportSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SportSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new SportSystem().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Dashbord;
    private javax.swing.JDialog EditAndDeleteManager;
    private javax.swing.JPanel FReport;
    private javax.swing.JPanel GenerateReports;
    private javax.swing.JPanel ListAllMembers;
    private javax.swing.JPanel MReport;
    private javax.swing.JPanel ManageManagers;
    private javax.swing.JPanel ManagePlayer;
    private javax.swing.JPanel ManageTeams;
    private javax.swing.JTextField ManagerSearch;
    private javax.swing.JPanel Parent;
    private javax.swing.JSpinner SDay;
    private javax.swing.JSpinner SMonth;
    private javax.swing.JSpinner SYear;
    private javax.swing.JComboBox<String> SearchBy;
    private javax.swing.JSpinner SpinnerSalary;
    private javax.swing.JPanel StatsAndAnalysis;
    private javax.swing.JPanel YReport;
    private javax.swing.JDialog addManager;
    private javax.swing.JButton btnAddTeam;
    private javax.swing.JButton btnCancelAddManager;
    private javax.swing.JButton btnCancelAddManager1;
    private javax.swing.JButton btnCancelAddManager2;
    private javax.swing.JButton btnExportF;
    private javax.swing.JButton btnExportM;
    private javax.swing.JButton btnExportY;
    private javax.swing.JButton btnFortnightlyReport;
    private javax.swing.JButton btnMonthlyReport;
    private javax.swing.JButton btnSaveAddManager;
    private javax.swing.JButton btnSaveAddManager1;
    private javax.swing.JButton btnYearlyReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JLabel lblGenerateReports;
    private javax.swing.JLabel lblListAllMembers;
    private javax.swing.JLabel lblManageManagers;
    private javax.swing.JLabel lblManagePlayer;
    private javax.swing.JLabel lblManageTeams;
    private javax.swing.JLabel lblSportSystem;
    private javax.swing.JLabel lblStatsAndAnalysis;
    private javax.swing.JLabel txtID;
    private javax.swing.JTextField txtmanagerAddress;
    private javax.swing.JTextField txtmanagerAddressOut;
    private javax.swing.JTextField txtmanagerBonus;
    private javax.swing.JTextField txtmanagerBonusOut;
    private javax.swing.JTextField txtmanagerDOB;
    private javax.swing.JTextField txtmanagerDOBOut;
    private javax.swing.JTextField txtmanagerName;
    private javax.swing.JTextField txtmanagerNameOut;
    private javax.swing.JTextField txtmanagerNationalityOut1;
    private javax.swing.JTextArea txtmanagerQuali;
    private javax.swing.JTextArea txtmanagerQualiOut;
    private javax.swing.JTextField txtmanagerSalaryOut;
    private javax.swing.JComboBox<String> txtmanagerTeam;
    private javax.swing.JComboBox<String> txtmanagerTeamOut;
    // End of variables declaration//GEN-END:variables

    // to set all the pages to false as example 
    private void setAllComponentsVisible(boolean visible) {
        for (Component component : Parent.getComponents()) {
            component.setVisible(visible);
        }
    }

    //
}
